# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ocr.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tocr.proto\x12\x03ocr\"\x19\n\nOcrRequest\x12\x0b\n\x03img\x18\x01 \x01(\x0c\"\x1a\n\x08OcrReply\x12\x0e\n\x06result\x18\x01 \x01(\t22\n\x03Ocr\x12+\n\x07\x43\x61llOcr\x12\x0f.ocr.OcrRequest\x1a\r.ocr.OcrReply\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ocr_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _OCRREQUEST._serialized_start=18
  _OCRREQUEST._serialized_end=43
  _OCRREPLY._serialized_start=45
  _OCRREPLY._serialized_end=71
  _OCR._serialized_start=73
  _OCR._serialized_end=123
# @@protoc_insertion_point(module_scope)
