# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import ocr_pb2 as ocr__pb2


class OcrStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CallOcr = channel.unary_unary(
                '/ocr.Ocr/CallOcr',
                request_serializer=ocr__pb2.OcrRequest.SerializeToString,
                response_deserializer=ocr__pb2.OcrReply.FromString,
                )


class OcrServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CallOcr(self, request, context):
        """我们rpc服务的名字
        后面
        服务端 会用到 <ComputeServicer>
        客户端 会用到 <ComputeStub>
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OcrServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CallOcr': grpc.unary_unary_rpc_method_handler(
                    servicer.CallOcr,
                    request_deserializer=ocr__pb2.OcrRequest.FromString,
                    response_serializer=ocr__pb2.OcrReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ocr.Ocr', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Ocr(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CallOcr(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ocr.Ocr/CallOcr',
            ocr__pb2.OcrRequest.SerializeToString,
            ocr__pb2.OcrReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
